Added functionality to use IAM roles
gametimesf/kinesis-connectors pull request #3
Opened 2016-10-03 23:27 UTC by shoumitra

@phacops

2016-10-03 23:56 UTC, phacops requested changes

2016-10-03 23:56 UTC, phacops commented on emitter/redshift/emitter.go
> +	IAM 			   string
Call it the same way `AwsIAMRole` or `IAMRole`.

2016-10-03 23:56 UTC, phacops commented on emitter/redshift/emitter.go
> +	if IAM != "" {
Don't you need a `e.IAM`?

2016-10-03 23:56 UTC, phacops commented on emitter/redshift/emitter.go
> +	s3 := &Emitter{Bucket: e.S3Bucket, Region: e.S3Region}
I don't see any `S3Region` on the emitter struct.

2016-10-04 00:14 UTC, phacops approved these changes

2016-10-04 00:15 UTC, merged

2016-10-04 19:29 UTC, jamietsao commented on emitter/redshift/emitter.go
> +		b.WriteString(fmt.Sprintf("CREDENTIALS '%v' ", e.IAM))
Hmm, shouldn't this be `e.IAMRole`?

2016-10-05 21:25 UTC, kylev commented on emitter/redshift/emitter.go
> +	IAMRole			   string
Note: this naming may cause an upstream pull request to stumble. Given the conventions in this repo, I'd name it `AwsIamRole`. Blending in is a great way to ensure a low-friction merge.